apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chrome
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.service: chrome
    spec:
      containers:
        - env:
            - name: HUB_HOST
              value: selenium-hub
            - name: HUB_PORT
              value: "4444"
          image: selenium/node-chrome:latest
          name: chrome
          resources: {}
          volumeMounts:
            - mountPath: /dev/shm
              name: chrome-claim0
      restartPolicy: Always
      volumes:
        - name: chrome-claim0
          persistentVolumeClaim:
            claimName: chrome-claim0
status: {}
