version: "2"
services:
  chrome:
    image: selenium/node-chrome:latest
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  selenium-hub:
    image: selenium/hub:latest
    restart: always
    container_name: selenium-hub
    ports:
      - "4444:4444"
  selenium-side-runner:
    build: .
    depends_on:
      - chrome
    volumes:
      - './sides:/sides'
      - './out:/root/out'

